---
title: "Assignment 1: Linear Models"
author: "Andrew Kerr"
format: 
  html:
    code-fold: true
    code-line-numbers: true
    code-tools: true
    embed-resources: true
editor: visual
---

```{r}
#| label: packages
#| message: false
#| warning: false

library(tidyverse)
library(tidymodels)
library(broom)
```

## Step 1

```{r}
#| label: data-read-in
#| message: false
ins <- read_csv(here::here("data", "insurance_costs_1.csv"))
```

## Step 2

#### Q1

```{r}
#| label: data-summary
ins %>% 
  count()

ins %>%
  summary()
```

#### Q2

```{r}
#| label: clean-data
ins <- ins %>%
  mutate(
    sex = as_factor(sex),
    smoker = as_factor(smoker),
    region = as_factor(region)
  )
```

#### Q3

```{r}
#| label: data-exploration
### Plot 1
ins %>%
  ggplot(mapping = aes(x = age, y = charges/1000, color = smoker)) +
  geom_point() +
  scale_y_continuous(labels = scales::label_dollar()) +
  scale_x_continuous(labels = function(x){paste(x, 'yrs')}) +
  labs(
    x = 'Age (years)',
    y = 'Charges (thousands of dollars)',
    color = 'Smoker') +
  theme_bw()

### Plot 2
ins %>%
  ggplot(mapping = aes(x = sex, y = charges/1000, fill = region)) +
  geom_boxplot() +
  scale_y_continuous(labels = scales::label_dollar()) +
  scale_x_discrete(labels = c('Female', 'Male')) +
  labs(
    x = 'Sex',
    y = 'Charges (thousands of dollars)',
    fill = 'Region'
  ) +
  theme_bw()

### Plot 3
ins %>%
  ggplot(mapping = aes(x = bmi, y = charges/1000, color = smoker)) +
  geom_point() +
  scale_y_continuous(labels = scales::label_dollar()) +
  labs(
    x = 'BMI',
    y = 'Charges (thousands of dollars)',
    color = 'Smoker') +
  theme_bw()
```

## Step 3

#### Q4

```{r}
#| label: age-model
lin_reg_spec <- linear_reg() %>%
  set_mode("regression") %>%
  set_engine("lm")

ins_lm_fit <- lin_reg_spec %>%
  fit(charges ~ age, data = ins) 
```

#### Q5

```{r}
#| label: age-coefs
# To get coefficient estimates, SEs, p-values, and CIs
tidy(ins_lm_fit) 
```

#### Q6

```{r}
#| label: age-metrics
# To model summary statistics
glance(ins_lm_fit)
```

#### Q7
```{r}
#| label: age*sex-model
ins_lm_fit2 <- lin_reg_spec %>%
  fit(charges ~ age*sex, data = ins) 

tidy(ins_lm_fit2)
```

#### Q8

#### Q9

#### Q10
```{r}
glance(ins_lm_fit2)$r.squared
glance(ins_lm_fit)$r.squared
#check this
```

#### Q11
```{r}
ins_lm_fit3 <- lin_reg_spec %>%
  fit(charges ~ age*smoker, data = ins) 

tidy(ins_lm_fit3)
```

#### Q12
```{r}
tidy(ins_lm_fit2)$std.error[1] / count(ins)
tidy(ins_lm_fit3)$std.error[1] / count(ins)
```

## Step 4

#### Q13
```{r}
ins_lm_fit4 <- lin_reg_spec %>%
  fit(charges ~ age + bmi, data = ins) 

tidy(ins_lm_fit4)
```

#### Q14

#### Q15
```{r}
glance(ins_lm_fit4)$r.squared
```

#### Q16

#### Q17
```{r}

```

#### Q18

#### Q19

#### Q20

#### Q21

```{r}
<YOUR DATASET> %>%
  ggplot() +
  geom_point(mapping = aes(x = age, y = charges)) +
  geom_line(mapping = aes(x = age, y = predicted_charges))

```

## Step 5

#### Q22

#### Q23

#### Q24

#### Q25
